### PR TITLE
Please look at this code!  Out of order sends RPC integration

### PR DESCRIPTION
**Pull request by mpmilano**
Hi team,

I built a reasonably clean Pseudo-allocator that allows programmers to use a `prepare_ordered_send` method on their cooked subgroups.  This produces a `message_builder`, which they can use to construct the individual arguments to their method (indexed by arg number, e.g. `bldr.build_arg<0>(...)`).

I'm confident in the `message_builder` classes, but I am *not* confident in the integration with `replicated_impl` and `remote_invocable`.  Would someone mind taking a look _before_ merging this PR in?  If this looks (and tests) as good, then the next step should be to reduce the super-redundant code that now exists on both the `ordered_send` and `prepare_ordered_send` paths.

### CODE REVIEW

**Comment by KenBirman** [comment]
One remark: as an API, this looks one-level more “internal” than I would have wished.

It seems to me that we are looking at yet another example in which some form of compile-time inspection feature for classes would eliminate a fairly ugly API (in this case, the numerical index for the method).

Right now Derecho hacks around this with our “tags” mechanism.  Two questions


1)      Could we simply use that same tags mechanism here, and replace these numbers (like the <0>) with a suitable tag (<myStruct:foo>)?

2)      Matthew mentioned that C++ was gradually coming around to a language feature that would let us eliminate the tags enumeration and generate the equivalent (a name-to-number constexpr map, where the names would be the names of fields and methods, and the numbers would be the index values).  Has this standards proposal moved forward?  If so, what would be the best timeframe for eliminating the Derecho tags and moving to that mechanism?

Ken

**Comment by mpmilano** [comment]
To @KenBirman's comments: 

First, to answer (2): it'll be a while.  The proposal looks like it'll be rejected from C++2a with a "needs more development" feedback, so the soonest we'll see it in a standard is ~2025, and it'd be a couple more years before widespread compiler support.  It could still surprise us and come sooner, but it'd definitely be a surprise. 

To answer (1): 

here's a snippet of a program using this API: 

```c++
auto msg_builder = cookedMessagesHandle.prepare_ordered_send<RPC_NAME(send)>(1024);
auto fst = msg_builder.template build_arg<0>(my_rank);
auto scnd = msg_builder.template build_arg<1>(i);
msg_builder.send(fst, scnd);
```

It's not immediately obvious what name you could use to replace the numbers here;  we can't use the types of the arguments to the RPC function, since those types aren't necessarily unique.  We also can't rely on the names given to those parameters at the function declaration point, because C++ doesn't even require that there *are* names at the declaration point.  It's perfectly legal to declare a function `void f(uint, uint){}` which never names its arguments.  Not just that, but *not* having those names is the assumed case;  `-Wall` will actually produce a warning if you choose to name an argument unnecessarily. 

Something that might make sense would be: 

```c++
declared_arg<uint> fst;
declared_arg<uint> scnd;
auto msg_builder = 
    cookedMessagesHandle.prepare_ordered_send<RPC_NAME(send)>(1024, fst, snd);
built_arg<uint> = fst.build(my_rank);
built_arg<uint> = scnd.build(i);
msg_builder.send(fst,scnd)
```

This allows programmers to specify an object which constructs each argument, which in turn gives them an opportunity to name that object however they'd like.  The only ugly bit is that it requires *two* intermediate objects for each argument; a "declared_arg" object and a "built_obj" object.  The reason for the extra `built_ptr` object is so that the type system has "evidence" that the user has actually bothered to construct their arguments before sending their message.  We'd like *something* that acts as a check that the arguments to this send have been completely initialized, and all the other things I could come up with involve passing a lambda as a constructor to either the initial `prepare_ordered_send` or to the final `send`.  Both of these seemed like a lot to put on one line. Here's an example of the lambda approach (which seems like too much to me): 

```c++
cookedMessagesHandle.prepared_ordered_send<RPC_NAME(send)>(1024, 
[&](builder<uint> &b) -> arg<uint>{
   //code that builds the first arg.  
   return b.build(my_rank);
},
[&](builder<uint> &b) -> arg<uint>{
   //code that builds the second arg.  
   return b.build(i);
},
[&](arg<uint> fst, arg<uint> scnd){
   //Code to run after everything is built
   //send implicitly called when this function ends.
}
)
```

**Comment by KenBirman** [comment]
Perhaps for now, the way to go is to show people two examples: first, an example passing a single argument, which is a struct that the application fills in field by field and then sends.  The advantage is of course that it becomes an uncooked send and hence benefits from our out of band sender side allocation.  On the receiver side, we batch opportunistically and hence can absorb some delay (for example if the receiver does a malloc and copy, to hold onto a copy of an incoming object).  For this case, with just a single argument, we could offer an non-templated instance of your API.

Then example two would be with multiple arguments and can use this positional notation.

As for names, though, I would ideally want a “group name” for all the polymorphic overloads of any given symbolic name.  All would get the same numerical index value.  Then we would leverage the compile time signature comparison feature (the one we already support) to figure out which of a set of overloads is the appropriate one.

**Comment by sagarjha** [comment]
Hi Matthew, I will have to take a closer look to check all the header assignments as we discussed with Edward that other day. Edward can probably do a better job.
But, I had written a test `deferred_send_test.cpp` that used raw RDMC out of order sends. It will be nice to make sure that the deferred sends also work with the cooked API, as per our intention. The test that you wrote is still sending messages in the order their memory is allocated from Derecho.

**Comment by mpmilano** [comment]
@sagarjha good point, I'll write a better test.

**Comment by sagarjha** [comment]
Closing this for now, since it has been open for a long time. It's not obvious that we will every accept this in master. If we decide to explore that possibility, we can reopen it.

**Pull request closed without merging**
